<a href="https://colab.research.google.com/github/Salah0Uddin/NLP_Learning/blob/main/NLP_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import tensorflow as tf

print("TensorFlow version:", tf.version.VERSION)

TensorFlow version: 2.18.0


In [30]:
print("Num GPUs available:", len(tf.config.list_physical_devices('GPU')))

Num GPUs available: 1


In [31]:
from tensorflow.keras.preprocessing.text import one_hot

In [32]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [33]:
### Vocabulary size
voc_size=500

In [34]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

# One Hot Representation

In [35]:
onehot_repr=[one_hot(word,voc_size)for word in sent]
print(onehot_repr)

[[399, 58, 75, 488], [399, 58, 75, 241], [399, 477, 75, 466], [431, 138, 228, 455, 253], [431, 138, 228, 455, 295], [104, 399, 352, 75, 355], [484, 211, 447, 455]]


# Word Embedding Represntation

In [36]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [37]:
import numpy as np


In [38]:
#pre-padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 399  58  75 488]
 [  0   0   0   0 399  58  75 241]
 [  0   0   0   0 399 477  75 466]
 [  0   0   0 431 138 228 455 253]
 [  0   0   0 431 138 228 455 295]
 [  0   0   0 104 399 352  75 355]
 [  0   0   0   0 484 211 447 455]]


In [39]:
## 10 feature dimesnions
dim=10

In [43]:
model = Sequential()
model.add(Embedding(input_dim=500, output_dim=10))
model.build(input_shape=(None, 8))
model.summary()



Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [45]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 399,  58,  75, 488], dtype=int32)

In [47]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step


array([[[-0.02185503,  0.01373584,  0.0094289 ,  0.04084362,
         -0.03906757,  0.02015429,  0.01812385,  0.04010978,
         -0.02372221,  0.02531309],
        [-0.02185503,  0.01373584,  0.0094289 ,  0.04084362,
         -0.03906757,  0.02015429,  0.01812385,  0.04010978,
         -0.02372221,  0.02531309],
        [-0.02185503,  0.01373584,  0.0094289 ,  0.04084362,
         -0.03906757,  0.02015429,  0.01812385,  0.04010978,
         -0.02372221,  0.02531309],
        [-0.02185503,  0.01373584,  0.0094289 ,  0.04084362,
         -0.03906757,  0.02015429,  0.01812385,  0.04010978,
         -0.02372221,  0.02531309],
        [-0.00621663,  0.03698846,  0.03818682, -0.04687846,
         -0.01824779, -0.00541193, -0.04891067, -0.04807972,
         -0.03370011, -0.02443135],
        [-0.0460546 ,  0.02640313, -0.03843451,  0.02811327,
          0.00478863, -0.02199653, -0.04052764,  0.01651477,
          0.02912339,  0.01618061],
        [-0.01120564,  0.03130366,  0.02859272,  0.0

In [55]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[[-2.18550321e-02,  1.37358420e-02,  9.42889601e-03,
          4.08436172e-02, -3.90675664e-02,  2.01542862e-02,
          1.81238540e-02,  4.01097797e-02, -2.37222072e-02,
          2.53130905e-02],
        [-2.18550321e-02,  1.37358420e-02,  9.42889601e-03,
          4.08436172e-02, -3.90675664e-02,  2.01542862e-02,
          1.81238540e-02,  4.01097797e-02, -2.37222072e-02,
          2.53130905e-02],
        [-2.18550321e-02,  1.37358420e-02,  9.42889601e-03,
          4.08436172e-02, -3.90675664e-02,  2.01542862e-02,
          1.81238540e-02,  4.01097797e-02, -2.37222072e-02,
          2.53130905e-02],
        [-2.18550321e-02,  1.37358420e-02,  9.42889601e-03,
          4.08436172e-02, -3.90675664e-02,  2.01542862e-02,
          1.81238540e-02,  4.01097797e-02, -2.37222072e-02,
          2.53130905e-02],
        [-6.21663406e-03,  3.69884633e-02,  3.81868221e-02,
         -4.68784571e-02, -1.82477944e-02, -5.41193411e-03,
         -4.89106663e-02, -4.80797179e-02, -3.370010

In [56]:
sent2=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [57]:
voc_size=1000

In [58]:
sent2

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [59]:
onehot_repr=[one_hot(word,voc_size)for word in sent2]
print(onehot_repr)

[[921, 783, 66, 405, 865, 407], [661, 956, 66, 214, 291, 302], [418, 115, 30, 421], [921, 256, 66, 663, 921, 615], [229, 809, 609, 66, 214, 291, 302], [986, 66, 214, 291, 424, 380]]


In [61]:
#pre padding
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [62]:
sent_length=10
embedded_docs=pad_sequences(onehot_repr,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 921 783  66 405 865 407]
 [  0   0   0   0 661 956  66 214 291 302]
 [  0   0   0   0   0   0 418 115  30 421]
 [  0   0   0   0 921 256  66 663 921 615]
 [  0   0   0 229 809 609  66 214 291 302]
 [  0   0   0   0 986  66 214 291 424 380]]


In [63]:
model=Sequential()
model.add(Embedding())

In [66]:
model=Sequential()
model.add(Embedding(voc_size,10,))
model.build(input_shape=(None, 10))
model.compile('adam','mse')

In [67]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 10, 10)         │        10,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,000 (39.06 KB)

 Trainable params: 10,000 (39.06 KB)

 Non-trainable params: 0 (0.00 B)

In [69]:
#The world is a better place
embedded_docs[0]

array([  0,   0,   0,   0, 921, 783,  66, 405, 865, 407], dtype=int32)

In [70]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step


array([[[-0.00856536, -0.04864797, -0.03913503, -0.02022322,
         -0.02458534,  0.0375538 , -0.02651345,  0.02408369,
         -0.02375157, -0.03168918],
        [-0.00856536, -0.04864797, -0.03913503, -0.02022322,
         -0.02458534,  0.0375538 , -0.02651345,  0.02408369,
         -0.02375157, -0.03168918],
        [-0.00856536, -0.04864797, -0.03913503, -0.02022322,
         -0.02458534,  0.0375538 , -0.02651345,  0.02408369,
         -0.02375157, -0.03168918],
        [-0.00856536, -0.04864797, -0.03913503, -0.02022322,
         -0.02458534,  0.0375538 , -0.02651345,  0.02408369,
         -0.02375157, -0.03168918],
        [-0.01598443,  0.04501947, -0.00387327, -0.00548538,
          0.02721219,  0.0467512 , -0.03785992, -0.0005532 ,
          0.01412085,  0.04368177],
        [-0.02818767, -0.03016187, -0.01978211,  0.00737022,
          0.01234734,  0.00767739, -0.02555348,  0.03542859,
         -0.0421754 ,  0.00963595],
        [ 0.03236772, -0.00317465,  0.04712318, -0.0

In [71]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step


array([[[-0.00856536, -0.04864797, -0.03913503, -0.02022322,
         -0.02458534,  0.0375538 , -0.02651345,  0.02408369,
         -0.02375157, -0.03168918],
        [-0.00856536, -0.04864797, -0.03913503, -0.02022322,
         -0.02458534,  0.0375538 , -0.02651345,  0.02408369,
         -0.02375157, -0.03168918],
        [-0.00856536, -0.04864797, -0.03913503, -0.02022322,
         -0.02458534,  0.0375538 , -0.02651345,  0.02408369,
         -0.02375157, -0.03168918],
        [-0.00856536, -0.04864797, -0.03913503, -0.02022322,
         -0.02458534,  0.0375538 , -0.02651345,  0.02408369,
         -0.02375157, -0.03168918],
        [-0.01598443,  0.04501947, -0.00387327, -0.00548538,
          0.02721219,  0.0467512 , -0.03785992, -0.0005532 ,
          0.01412085,  0.04368177],
        [-0.02818767, -0.03016187, -0.01978211,  0.00737022,
          0.01234734,  0.00767739, -0.02555348,  0.03542859,
         -0.0421754 ,  0.00963595],
        [ 0.03236772, -0.00317465,  0.04712318, -0.0

**"The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"**

all of each sentences is converted to vectors