<a href="https://colab.research.google.com/github/Salah0Uddin/NLP_Learning/blob/main/NLP_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install nltk

In [ ]:
paragraph='''
Elon Reeve Musk was born on June 28, 1971, in Pretoria, South Africa's administrative capital.[2][3] He is of British and Pennsylvania Dutch ancestry.[4][5] His mother, Maye (née Haldeman), is a model and dietitian born in Saskatchewan, Canada, and raised in South Africa.[6][7][8] His father, Errol Musk, is a South African electromechanical engineer, pilot, sailor, consultant, emerald dealer, and property developer, who partly owned a rental lodge at Timbavati Private Nature Reserve.[9][10][11][12] His maternal grandfather, Joshua N. Haldeman, who died in a plane crash when Elon was a toddler, was an American-born Canadian chiropractor, aviator and political activist in the Technocracy movement[13][14] who moved to South Africa in 1950.[15] Haldeman's anti-government, anti-democratic and conspiracist views, which included the promotion of far-right antisemitic conspiracy theories,[16][17] "fanatical" support of apartheid,[17] and according to Errol Musk, support of Nazism,[18] have been suggested as an influence on Elon.[19][20][21][22] During his childhood, Elon was told stories by his grandmother of Haldeman's travels and exploits, and Elon has suggested that all of Haldeman's descendants have his "desire for adventure, exploration – doing crazy things".[23]

Elon has a younger brother, Kimbal, a younger sister, Tosca, and four paternal half-siblings.[24][25][8][26] Musk was raised in the Anglican Church, in which he was baptized.[27][28] The Musk family was wealthy during Elon's youth.[12] Despite both Elon and Errol previously stating that Errol was a part owner of a Zambian emerald mine,[12] in 2023, Errol recounted that the deal he made was to receive "a portion of the emeralds produced at three small mines".[29][30] Errol was elected to the Pretoria City Council as a representative of the anti-apartheid Progressive Party and has said that his children shared their father's dislike of apartheid.
'''

In [ ]:
paragraph

'\nElon Reeve Musk was born on June 28, 1971, in Pretoria, South Africa\'s administrative capital.[2][3] He is of British and Pennsylvania Dutch ancestry.[4][5] His mother, Maye (née Haldeman), is a model and dietitian born in Saskatchewan, Canada, and raised in South Africa.[6][7][8] His father, Errol Musk, is a South African electromechanical engineer, pilot, sailor, consultant, emerald dealer, and property developer, who partly owned a rental lodge at Timbavati Private Nature Reserve.[9][10][11][12] His maternal grandfather, Joshua N. Haldeman, who died in a plane crash when Elon was a toddler, was an American-born Canadian chiropractor, aviator and political activist in the Technocracy movement[13][14] who moved to South Africa in 1950.[15] Haldeman\'s anti-government, anti-democratic and conspiracist views, which included the promotion of far-right antisemitic conspiracy theories,[16][17] "fanatical" support of apartheid,[17] and according to Errol Musk, support of Nazism,[18] hav

In [ ]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

**Tokenization converting sentence to words**

In [ ]:
nltk.download("punkt")
nltk.download("punkt_tab")
sentences=nltk.sent_tokenize(paragraph)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [ ]:
sentences

["\nElon Reeve Musk was born on June 28, 1971, in Pretoria, South Africa's administrative capital.",
 '[2][3] He is of British and Pennsylvania Dutch ancestry.',
 '[4][5] His mother, Maye (née Haldeman), is a model and dietitian born in Saskatchewan, Canada, and raised in South Africa.',
 '[6][7][8] His father, Errol Musk, is a South African electromechanical engineer, pilot, sailor, consultant, emerald dealer, and property developer, who partly owned a rental lodge at Timbavati Private Nature Reserve.',
 '[9][10][11][12] His maternal grandfather, Joshua N. Haldeman, who died in a plane crash when Elon was a toddler, was an American-born Canadian chiropractor, aviator and political activist in the Technocracy movement[13][14] who moved to South Africa in 1950.',
 '[15] Haldeman\'s anti-government, anti-democratic and conspiracist views, which included the promotion of far-right antisemitic conspiracy theories,[16][17] "fanatical" support of apartheid,[17] and according to Errol Musk, s

In [ ]:
type(sentences)

list

In [ ]:
stemmer=PorterStemmer()


In [ ]:
stemmer.stem("going")

'go'

In [ ]:
stemmer.stem("History")

'histori'

In [ ]:
from nltk.stem import WordNetLemmatizer

In [ ]:
lemmatizer=WordNetLemmatizer()

In [ ]:
nltk.download("wordnet")
lemmatizer.lemmatize("History")

[nltk_data] Downloading package wordnet to /root/nltk_data...


'History'

In [ ]:
import re

In [ ]:
len(sentences)

12

In [ ]:
#cleaning the corpus
corpus=[]

for i in range(len(sentences)):
  review=re.sub("[^a-zA-Z]"," ",sentences[i])
  review=review.lower()
  review=review.split()
  review=" ".join(review)
  corpus.append(review)

In [ ]:
corpus

['elon reeve musk was born on june in pretoria south africa s administrative capital',
 'he is of british and pennsylvania dutch ancestry',
 'his mother maye n e haldeman is a model and dietitian born in saskatchewan canada and raised in south africa',
 'his father errol musk is a south african electromechanical engineer pilot sailor consultant emerald dealer and property developer who partly owned a rental lodge at timbavati private nature reserve',
 'his maternal grandfather joshua n haldeman who died in a plane crash when elon was a toddler was an american born canadian chiropractor aviator and political activist in the technocracy movement who moved to south africa in',
 'haldeman s anti government anti democratic and conspiracist views which included the promotion of far right antisemitic conspiracy theories fanatical support of apartheid and according to errol musk support of nazism have been suggested as an influence on elon',
 'during his childhood elon was told stories by his 

In [ ]:
#Stemming

nltk.download("stopwords")
for i in corpus:
  words=nltk.word_tokenize(i)
  for word in words:
    if word not in set(stopwords.words("english")):
      print(stemmer.stem(word))

elon
reev
musk
born
june
pretoria
south
africa
administr
capit
british
pennsylvania
dutch
ancestri
mother
may
n
e
haldeman
model
dietitian
born
saskatchewan
canada
rais
south
africa
father
errol
musk
south
african
electromechan
engin
pilot
sailor
consult
emerald
dealer
properti
develop
partli
own
rental
lodg
timbavati
privat
natur
reserv
matern
grandfath
joshua
n
haldeman
die
plane
crash
elon
toddler
american
born
canadian
chiropractor
aviat
polit
activist
technocraci
movement
move
south
africa
haldeman
anti
govern
anti
democrat
conspiracist
view
includ
promot
far
right
antisemit
conspiraci
theori
fanat
support
apartheid
accord
errol
musk
support
nazism
suggest
influenc
elon
childhood
elon
told
stori
grandmoth
haldeman
travel
exploit
elon
suggest
haldeman
descend
desir
adventur
explor
crazi
thing
elon
younger
brother
kimbal
younger
sister
tosca
four
patern
half
sibl
musk
rais
anglican
church
baptiz
musk
famili
wealthi
elon
youth
despit
elon
errol
previous
state
errol
part
owner
zambian

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
#lemmatization

for i in corpus:
  words=nltk.word_tokenize(i)
  for word in words:
    if word not in set(stopwords.words("english")):
      word=lemmatizer.lemmatize(word)
      print(word)

elon
reeve
musk
born
june
pretoria
south
africa
administrative
capital
british
pennsylvania
dutch
ancestry
mother
maye
n
e
haldeman
model
dietitian
born
saskatchewan
canada
raised
south
africa
father
errol
musk
south
african
electromechanical
engineer
pilot
sailor
consultant
emerald
dealer
property
developer
partly
owned
rental
lodge
timbavati
private
nature
reserve
maternal
grandfather
joshua
n
haldeman
died
plane
crash
elon
toddler
american
born
canadian
chiropractor
aviator
political
activist
technocracy
movement
moved
south
africa
haldeman
anti
government
anti
democratic
conspiracist
view
included
promotion
far
right
antisemitic
conspiracy
theory
fanatical
support
apartheid
according
errol
musk
support
nazism
suggested
influence
elon
childhood
elon
told
story
grandmother
haldeman
travel
exploit
elon
suggested
haldeman
descendant
desire
adventure
exploration
crazy
thing
elon
younger
brother
kimbal
younger
sister
tosca
four
paternal
half
sibling
musk
raised
anglican
church
baptized
m

In [ ]:
#BOG(Bag of words)
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [ ]:
X=cv.fit_transform(corpus)

In [ ]:
cv.vocabulary_

{'elon': 54,
 'reeve': 119,
 'musk': 93,
 'was': 150,
 'born': 20,
 'on': 97,
 'june': 81,
 'in': 76,
 'pretoria': 109,
 'south': 131,
 'africa': 4,
 'administrative': 2,
 'capital': 27,
 'he': 74,
 'is': 79,
 'of': 96,
 'british': 22,
 'and': 10,
 'pennsylvania': 104,
 'dutch': 51,
 'ancestry': 9,
 'his': 75,
 'mother': 90,
 'maye': 86,
 'haldeman': 70,
 'model': 89,
 'dietitian': 47,
 'saskatchewan': 126,
 'canada': 25,
 'raised': 116,
 'father': 64,
 'errol': 58,
 'african': 5,
 'electromechanical': 53,
 'engineer': 57,
 'pilot': 105,
 'sailor': 125,
 'consultant': 35,
 'emerald': 55,
 'dealer': 40,
 'property': 115,
 'developer': 45,
 'who': 154,
 'partly': 101,
 'owned': 98,
 'rental': 120,
 'lodge': 83,
 'at': 16,
 'timbavati': 143,
 'private': 111,
 'nature': 94,
 'reserve': 122,
 'maternal': 85,
 'grandfather': 68,
 'joshua': 80,
 'died': 46,
 'plane': 106,
 'crash': 37,
 'when': 152,
 'toddler': 145,
 'an': 8,
 'american': 7,
 'canadian': 26,
 'chiropractor': 30,
 'aviator': 1

In [ ]:
corpus[0]

'elon reeve musk was born on june in pretoria south africa s administrative capital'

In [ ]:
X[0].toarray()

array([[0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0]])

**TF IDF**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer(ngram_range=(1,1))
X=cv.fit_transform(corpus)

In [ ]:
corpus[0]

'elon reeve musk was born on june in pretoria south africa s administrative capital'

In [ ]:
X[0].toarray()

array([[0.        , 0.        , 0.34529026, 0.        , 0.26194992,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.26194992, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.34529026, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.17860958,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

## Word2vec


In [ ]:
!pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 70.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 66.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 14.7 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tsfresh 0.21.0 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
thinc 8.3.6 req

In [ ]:
import gensim

In [ ]:
from gensim.models import Word2Vec,keyedvectors

In [ ]:
import gensim.downloader as api

wv=api.load("word2vec-google-news-300")

vec_king=wv["king"]

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [ ]:
wv["man"]

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [ ]:
wv.most_similar("man")

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [ ]:
wv.most_similar("king")

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [ ]:
wv.similarity("man","king")

0.22942673

In [ ]:
wv.similarity("html","boy")

-0.02857274

In [ ]:
wv.similarity("women","Man")

0.12635618

In [ ]:
wv.similarity("html","Programmer")

0.18460625